query sendSinglePrompt(
  $input: String!
  $skipCache: Boolean
  $indexesReturned: [Int!]
  $resultIndexFromCache: Int
) {
  sendSinglePrompt(
    input: $input
    skipCache: $skipCache
    indexesReturned: $indexesReturned
    resultIndexFromCache: $resultIndexFromCache
  ) {
    result
    resultIndex
    error
    totalResultsInCache
  }
}
